### ISSUE TITLE
Precompilation of plotting extension fails

### ISSUE THREAD

**Issue by jagot** [complexvariables/RationalFunctionApproximation.jl#6]
Thank you for this beautiful package!

When loading RationalFunctionApproximation.jl after having loaded GLMakie, the RFAMakiExt extension kicks in. However, it fails to precompile with the following message:

```
WARNING: Method definition errorplot(RationalFunctionApproximation.Approximation{T, S} where S where T) in module RationalFunctionApproximation at /Users/jagot/.julia/packages/RationalFunctionApproximation/9jY5B/src/RationalFunctionApproximation.jl:31 overwritten in module RFAMakieExt at /Users/jagot/.julia/packages/RationalFunctionApproximation/9jY5B/ext/RFAMakieExt.jl:34.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
```

i.e.

https://github.com/complexvariables/RationalFunctionApproximation.jl/blob/f48ed4ca74dea8a7acbc668faf7943a61ad9ff00/src/RationalFunctionApproximation.jl#L31-L33

is overwritten by

https://github.com/complexvariables/RationalFunctionApproximation.jl/blob/f48ed4ca74dea8a7acbc668faf7943a61ad9ff00/ext/RFAMakieExt.jl#L29-L55

Maybe it is better to replace the function stub by an empty function?
```julia
function errorplot end
```
and similarly for `convergenceplot`?

**Comment by zinkkkk** [comment]
I don't have much to add other than having the same issues when trying to follow most of the examples walkthrough page
